### PR TITLE
added cbse syllabi

### PR DESCRIPTION
**Pull request by Tharani-G**
syllabi

### CODE REVIEW

**Comment by ajith0606** [comment]
tq broo  by vex squde

**Comment by Tharani-G** [comment]
its ok da broo

**Comment by ajith0606** [comment]
ok daa

**Comment by Tharani-G** [comment]
mmm...

**Comment by ajith0606** [comment]
mm

**Comment by Tharani-G** [comment]
.

**Comment by ajith0606** [comment]
mkh

**Pull request merged**
